"""add subscriptions.manual_override

Revision ID: 3a71b571d713
Revises: 1fb298a6e73b
Create Date: 2026-08-04 19:45:26.456897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a71b571d713'
down_revision: Union[str, None] = '1fb298a6e73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this is safe even if the table isn't empty when this
    # runs (it is today -- nothing writes to `subscriptions` yet -- but
    # NOT NULL without a default would fail on Postgres against existing
    # rows).
    op.add_column(
        'subscriptions',
        sa.Column('manual_override', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'manual_override')
    # ### end Alembic commands ###
